platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'RXDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RXSDK_Pure'
#  pod 'RXIMSDK-iOS'

end
